[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
wasm_opt = false

[watch]
ignore = ["./dist", "./target"]

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false

[clean]
cargo = true
